list: $/squanbri/authentication/models/companies/columns.yaml
modelClass: Squanbri\Authentication\Models\Companies
title: Company
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'squanbri/authentication/company/update/:id'
